# Generated by Django 4.0.4 on 2022-05-27 09:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('course_name', models.CharField(choices=[('AI', 'Artificial Intelligence'), ('GT', 'Computer Games Technology'), ('CS', 'Cyber Security '), ('DS', 'Data Science'), ('CC', 'Software Engineering with Cloud Computing'), ('HC', 'Human-Computer Interaction Design')], max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('fid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('field_title', models.CharField(max_length=200, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('image_profile', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('linkedIn_link', models.CharField(blank=True, max_length=250, null=True)),
                ('github_link', models.CharField(blank=True, max_length=250, null=True)),
                ('portfolio', models.CharField(blank=True, max_length=250, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='thesis.person')),
                ('cis', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='thesis.course')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('suid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='thesis.person')),
                ('fields', models.ManyToManyField(to='thesis.field')),
            ],
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('tid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='thesis.field')),
                ('stid', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='thesis.student')),
                ('suid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='thesis.supervisor')),
            ],
        ),
    ]
